eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUri:
      defaultZone:http://${eureka.instance.hostname}:${server.port}/eureka
